### ISSUE TITLE
lookup 出错

### ISSUE THREAD

**Issue by zpxlz** [YouChenJun/Keydd#5]
证书已安装，包括双击安装和浏览器导入安装。

浏览器挂yakit代理，如下
![image](https://github.com/user-attachments/assets/4e1ff90f-7761-4183-9f3d-fd0536c7d1cd)

Yakit下游代理配置，
![image](https://github.com/user-attachments/assets/81f7e2f5-7d97-4392-ac08-9454234b3e99)

工具开启，访问百度，报错如下，
![image](https://github.com/user-attachments/assets/57b6a38f-95ff-49ed-bcd4-81db87ad4648)

**Comment by YouChenJun** [comment]
请检查一下yakit的DNS设置，需要在yakit自己选择一个DNS服务器
