### ISSUE TITLE
能增加下游代理功能吗

### ISSUE THREAD

**Issue by n1utra** [YouChenJun/Keydd#6]
想在工具下游设置xray等工具

**Comment by YouChenJun** [comment]
这个需求暂时不考虑，因为工具过多套嵌的意义不大，这个工具可以设置为xray的下游代理

**Comment by lovelyjuice** [comment]
设成xray的下游代理性能损失就太大了，一个包进了xray出来能多100个包

**Comment by lovelyjuice** [comment]
可以用proxifier强制它走xray
